// Faz 8B.1 - single mutable application state
export const state = {
    db: null,
    auth: null,
    authUser: null,
    userProfile: null,
    authReady: false,
    demoMode: localStorage.getItem("usoap_phase7_demo_mode") === "true",
    notificationReads: JSON.parse(localStorage.getItem("usoap_phase7_notification_reads") || "[]"),
    firebaseReady: false,
    firebaseMessage: "Bağlantı denenmedi",
    editProgramId: null,
    editAuditId: null,
    currentAuditFileId: localStorage.getItem("usoap_phase3a_current_audit_file") || "",
    currentAuditeeResponseAuditId: localStorage.getItem("usoap_phase3b_current_response_audit") || "",
    currentPreEvaluationAuditId: localStorage.getItem("usoap_phase3b_current_preeval_audit") || "",
    currentAuditExecutionId: localStorage.getItem("usoap_phase4_current_execution_audit") || "",
    currentObjectionAuditId: localStorage.getItem("usoap_phase5_current_objection_audit") || "",
    currentFinalReportAuditId: localStorage.getItem("usoap_phase5_current_final_report_audit") || "",
    programFilters: { search: "", status: "all", year: "all" },
    auditFilters: { search: "", programId: "all", method: "all", type: "all", dateFrom: "", dateTo: "" },
    role: localStorage.getItem("usoap_phase1_role") || "admin",
    orgContext: localStorage.getItem("usoap_phase1_org") || "org_demo",
    currentSection: "home",
    masterRows: [],
    normalizedAreas: {},
    users: [],
    auditPrograms: [],
    audits: [],
    auditAssignments: [],
    organizationResponses: [],
    auditPreEvaluations: [],
    auditResponses: [],
    organizations: [],
    findings: [],
    capPlans: [],
    capSteps: [],
    reports: [],
    formRevisions: []
  };
